# Generated by Django 5.0.6 on 2024-07-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_expertise_alter_user_hobbies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.TextField(max_length=255),
        ),
    ]
