# Generated by Django 5.0.6 on 2024-07-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drinking_status',
            field=models.CharField(choices=[('Non-drinker', 'Non-drinker'), ('Drinker', 'Drinker'), ('Occasional', 'Occasional')], default='Non-drinker', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='smoking_status',
            field=models.CharField(choices=[('Non-smoker', 'Non-smoker'), ('Smoker', 'Smoker'), ('Occasional', 'Occasional')], default='Non-smoker', max_length=20),
        ),
    ]
