# Generated by Django 5.0.6 on 2024-07-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_drinking_status_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qualification',
            field=models.CharField(choices=[('SSLC', 'SSLC'), ('PLUSTWO', 'PLUSTWO'), ('BACHELOR', 'BACHELOR'), ('MASTERS', 'MASTERS'), ('PHD', 'PHD')], max_length=255),
        ),
    ]
