# Generated by Django 5.0.6 on 2024-07-04 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(blank=True, max_length=255)),
                ('fathers_job', models.CharField(blank=True, max_length=255)),
                ('mothers_name', models.CharField(blank=True, max_length=255)),
                ('mothers_job', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parentsdet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
