# Generated by Django 5.0.6 on 2024-07-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_partnerpreferance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsdetails',
            name='fathers_job',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parentsdetails',
            name='fathers_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parentsdetails',
            name='mothers_job',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parentsdetails',
            name='mothers_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerpreferance',
            name='age',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerpreferance',
            name='caste',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerpreferance',
            name='height',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerpreferance',
            name='income',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerpreferance',
            name='religion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerpreferance',
            name='weight',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='caste',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='height',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='horriscope',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='income',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='religion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='weight',
            field=models.CharField(max_length=255),
        ),
    ]
