# Generated by Django 5.0.6 on 2024-07-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_parentsdetails_fathers_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerpreferance',
            name='age',
        ),
        migrations.RemoveField(
            model_name='partnerpreferance',
            name='height',
        ),
        migrations.RemoveField(
            model_name='partnerpreferance',
            name='weight',
        ),
        migrations.AddField(
            model_name='partnerpreferance',
            name='max_age',
            field=models.CharField(default='99', max_length=255),
        ),
        migrations.AddField(
            model_name='partnerpreferance',
            name='max_height',
            field=models.CharField(default='200', max_length=255),
        ),
        migrations.AddField(
            model_name='partnerpreferance',
            name='max_weight',
            field=models.CharField(default='100', max_length=255),
        ),
        migrations.AddField(
            model_name='partnerpreferance',
            name='min_age',
            field=models.CharField(default='18', max_length=255),
        ),
        migrations.AddField(
            model_name='partnerpreferance',
            name='min_height',
            field=models.CharField(default='150', max_length=255),
        ),
        migrations.AddField(
            model_name='partnerpreferance',
            name='min_weight',
            field=models.CharField(default='50', max_length=255),
        ),
    ]
