# Generated by Django 5.0.6 on 2024-07-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_partnerpreferance_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerpreferance',
            name='income',
        ),
        migrations.RemoveField(
            model_name='partnerpreferance',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='partnerpreferance',
            name='max_height',
        ),
        migrations.RemoveField(
            model_name='partnerpreferance',
            name='max_weight',
        ),
        migrations.RemoveField(
            model_name='partnerpreferance',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='partnerpreferance',
            name='min_height',
        ),
        migrations.RemoveField(
            model_name='partnerpreferance',
            name='min_weight',
        ),
        migrations.AddField(
            model_name='partnerpreferance',
            name='age_max',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='partnerpreferance',
            name='age_min',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='partnerpreferance',
            name='height_max',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name='partnerpreferance',
            name='height_min',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='partnerpreferance',
            name='income_max',
            field=models.PositiveIntegerField(default=200000),
        ),
        migrations.AddField(
            model_name='partnerpreferance',
            name='income_min',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='partnerpreferance',
            name='qualification',
            field=models.CharField(choices=[('SSLC', 'SSLC'), ('PLUSTWO', 'Plus Two'), ('BACHELOR', 'Bachelors'), ('MASTERS', 'Masters'), ('PHD', 'PhD')], default='PLUSTWO', max_length=50),
        ),
        migrations.AddField(
            model_name='partnerpreferance',
            name='weight_max',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='partnerpreferance',
            name='weight_min',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='partnerpreferance',
            name='caste',
            field=models.CharField(choices=[('Brahmin', 'Brahmin'), ('Kshatriya', 'Kshatriya'), ('Vaishya', 'Vaishya'), ('Shudra', 'Shudra'), ('Dalit', 'Dalit'), ('Koli', 'Koli'), ('Gujar', 'Gujar'), ('Lodhi', 'Lodhi'), (' Yadav', 'Yadav'), ('Jat', 'Jat'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='partnerpreferance',
            name='religion',
            field=models.CharField(choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Sikhism', 'Sikhism'), ('Judaism', 'Judaism'), ('Baha’i', 'Baha’i'), ('Jainism', 'Jainism'), ('Shintoism', 'Shintoism'), ('Cao Dai', 'Cao Dai'), ('Others', 'Others')], max_length=100),
        ),
    ]
