# Generated by Django 5.0.6 on 2024-07-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_partnerpreferance_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='country',
            field=models.CharField(choices=[('INDIA', 'India')], default='NONE', max_length=10, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='district',
            field=models.CharField(choices=[('WAYANAD', 'Wayanad'), ('THRISSUR', 'Thrissur'), ('THIRUVANANTHAPURAM', 'Thiruvananthapuram'), ('PATHANAMTHITTA', 'Pathanamthitta'), ('PALAKKAD', 'Palakkad'), ('MALAPPURAM', 'Malappuram'), ('KOTTAYAM', 'Kottayam'), ('KOLLAM', 'Kollam'), ('KOZHIKODE', 'Kozhikode'), ('KASARKODE', 'Kasarkode'), ('IDUKKI', 'Idukki'), ('ERNAKULAM', 'Ernakulam'), ('ALAPPUZHA', 'Alappuzha')], default='NONE', max_length=100, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='fathers_job',
            field=models.CharField(default='sales', max_length=255),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='fathers_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='mothers_job',
            field=models.CharField(default='sales', max_length=255),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='mothers_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='permanent_address',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='present_address',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='siblings',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='state',
            field=models.CharField(choices=[('KERALA', 'Kerala'), ('TAMILNADU', 'Tamilnadu')], default='NONE', max_length=100, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='partnerpreferance',
            name='qualification',
            field=models.CharField(choices=[('SSLC', 'SSLC'), ('PLUSTWO', 'Plus Two'), ('BACHELOR', 'Bachelors'), ('MASTERS', 'Masters'), ('PHD', 'PhD'), ('BCOM', 'bcom')], default='PLUSTWO', max_length=50),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='caste',
            field=models.CharField(choices=[('Brahmin', 'Brahmin'), ('Kshatriya', 'Kshatriya'), ('Vaishya', 'Vaishya'), ('Shudra', 'Shudra'), ('Dalit', 'Dalit'), ('Koli', 'Koli'), ('Gujar', 'Gujar'), ('Lodhi', 'Lodhi'), (' Yadav', 'Yadav'), ('Jat', 'Jat'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='horriscope',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='income',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='religion',
            field=models.CharField(choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Sikhism', 'Sikhism'), ('Judaism', 'Judaism'), ('Baha’i', 'Baha’i'), ('Jainism', 'Jainism'), ('Shintoism', 'Shintoism'), ('Cao Dai', 'Cao Dai'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='ParentsDetails',
        ),
    ]
