# Generated by Django 5.0.6 on 2024-07-14 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_personaldetails_country_personaldetails_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerpreferance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partnerpreferance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='horriscope',
            field=models.FileField(upload_to='horoscopes/'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='income',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
