# Generated by Django 5.0 on 2024-07-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_subscription_amount_subscription_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='siblings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
